[Icon Theme]
Name=Clean
Comment=Clean Icon Theme
Directories=scalable/apps
Inherits=Adwaita,breeze,hicolor

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,24,32,48,64
ToolbarDefault=22
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=48
PanelSizes=16,22,24,32,48,64
DialogDefault=48
DialogSizes=16,22,24,32,48,64

[scalable/apps]
Size=48
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable
